---
- name: Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  listen: "restart"

- name: Wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  listen: "restart"
